spec:
  template:
    spec:
      containers:
        - name: vertx
          env:
            - name: SENTIMENT_APIKEY
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: sentiment-api-key
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.runArgs="-Dvertx.disableDnsResolver=true"'
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: "/api/health/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreashold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/api/health/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreashold: 1
            timeoutSeconds: 1
